### PR TITLE
fix pg_stat_statement query: add queryid to make it unique

### PR DESCRIPTION
**Pull request by TLINDEN**
Fixes https://github.com/metal-stack/helm-charts/issues/86

### CODE REVIEW

**Review by eberlep — APPROVED** [review]
Reviewed and already tested.

**Comment by Gerrit91** [comment]
I still play around with the metal-robot and the fork builds, please ignore when I continue commenting on this issue. 😅

/ok-to-build

**Comment by Gerrit91** [comment]
Is this going to be merged or not? If not required anymore, please close.

**Comment by TLINDEN** [comment]
Yes, we still need this patch.

**Comment by TLINDEN** [comment]
versions must be bumped.

**Comment by TLINDEN** [comment]
Replaced by https://github.com/metal-stack/helm-charts/pull/94

**Pull request closed without merging**
